"""リポジトリ抽象。Mock（MVP）↔ Firestore（将来）の差し替えの継ぎ目。"""

from __future__ import annotations

from typing import Optional, Protocol

from publishr_schema import Book, Persona, Plan, User


class RepositoryProtocol(Protocol):
    def list_books(
        self, status: Optional[str] = None, shelf: Optional[str] = None
    ) -> list[Book]: ...

    def get_book(self, book_id: str) -> Optional[Book]: ...

    def upsert_book(self, book: Book) -> Book: ...

    def reserve_book_atomic(
        self, book_id: str, *, owner_uid: str = "", max_concurrent: int = 5
    ) -> Book: ...

    def list_plans(self) -> list[Plan]: ...

    def get_plan(self, plan_id: str) -> Optional[Plan]: ...

    def list_personas(self) -> list[Persona]: ...

    def get_persona(self, persona_id: str) -> Optional[Persona]: ...

    def upsert_persona(self, persona: Persona) -> Persona: ...

    def list_users(self) -> list[User]: ...

    def get_user(self, user_id: str) -> Optional[User]: ...

    def upsert_user(self, user: User) -> User: ...

    # ── 企画 run の冪等ロック（I-38: Pub/Sub 再配信ストーム対策）─────────────
    # 重い planning worker は ack_deadline を超えて Pub/Sub 再配信され得る。run_id を鍵に
    # 「最初の1回だけ処理し、再配信は skip」する server 所有ロック。begin が True を返した
    # caller だけが処理を進め、完了/失敗を記録する。
    def begin_planning_run(self, run_id: str, owner_uid: str, user_id: str) -> bool: ...

    def complete_planning_run(self, run_id: str, book_ids: list[str]) -> None: ...

    def fail_planning_run(self, run_id: str, error_type: str) -> None: ...
